package com.cognitionis.tipsem;

public enum TipSemAction {
	 ANNOTATECRF,
	    ANNOTATE, TAN, //TIMEX, EVENT, TE3,   GET_FEATURES4PLAIN, GET_FEATURES4TAB,   TIMEKPRUEBAS,   SEGMENT_SENTENCE_PRUEBAS
	    TRAIN_AND_TEST, //TRAIN_RECOGNITION_TML, TRAIN_CLASSIFICATION_TML, TRAIN_NORMALIZATIONTYPE_TML, TRAIN_CATEGORIZATION_TML,
	    TEST_NORMALIZATION_TML, //TRAIN_RECOGNITION, TRAIN_CLASSIFICATION, TRAIN_NORMALIZATIONTYPE, TRAIN_CATEGORIZATION, TEST_NORMALIZATION,
	    //TML2ISOTML, ISOTML2TML, TML2TE3, // can be unified in one
	    PLAIN2TE3,
	    CONVERT_TML, DATASET2TML, RECOGNITION2TML,
	    //DATASET2REMOVE_ES_TOBE_STATES, DATASET2TML, TML2DATASET4MODEL, TMLDIR2DATASET4MODEL,   // se puede eliminar o unir con las anteriores
	    UTF_2_ISO_8859_1_SAFE_UTF,
	    TML_NFOLD //, TAB_NFOLD, TEMPEVAL_RECOGNITION_10FOLD, TEMPEVAL_CLASSIFICATION_10FOLD,
	    
}
